apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ehsmeyyqb-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: nexus-docker-nexus.apps.rosa.rhtap-services.xmdt.p3.openshiftapps.com/rhtap/rhtap-qe-java-quarkus:7313c3ea78a5878a8d452edbfaefc7c3cdfaf923@sha256:93c6b85ea09094088eb8cd7dadf82b42319a3d412f8ea0d3f7c9fae1eb8e0762
          name: container-image
